# Generated by Django 4.2.7 on 2023-12-28 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contratelectronique',
            fields=[
                ('id_contrat', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_vendeur', models.CharField(max_length=25)),
                ('nom_prenant', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Contratelectronique',
                'verbose_name_plural': 'Contratelectroniques',
            },
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id_contrat', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Proprio',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
                ('birthdate', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('id_proprio', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personne',
                'verbose_name_plural': 'Personnes',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id_pay', models.BigAutoField(primary_key=True, serialize=False)),
                ('montant', models.IntegerField(null=True)),
                ('contratelectronique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locimo.contratelectronique')),
            ],
            options={
                'verbose_name': 'pay',
                'verbose_name_plural': 'payers',
            },
        ),
        migrations.AddField(
            model_name='contratelectronique',
            name='proprio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locimo.proprio'),
        ),
        migrations.CreateModel(
            name='Agenceimo',
            fields=[
                ('id_agence', models.BigAutoField(primary_key=True, serialize=False)),
                ('agency_name', models.CharField(max_length=20)),
                ('background_image', models.ImageField(upload_to='')),
                ('profile_image', models.ImageField(upload_to='')),
                ('description', models.TextField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('proprio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locimo.proprio')),
            ],
            options={
                'verbose_name': 'Agenceimo',
                'verbose_name_plural': 'Agenceimos',
            },
        ),
    ]
